config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  resources :companies, only: %i[index] do
    get 'search_name', on: :collection
    member do
      get 'profile'
      get 'jobs'
    end
  end

  devise_for :candidates

  devise_for :employees, controllers: {
    registrations: 'employees/registrations'
  }
  
  namespace :employees_backoffice do
    root 'home#index'
    resources :employees, only: %i[show edit update]

    resources :jobs, only: %i[index new create show edit update]
    
    resources :companies, only: %i[show edit update] do
      member do
        get 'profile'
      end
    end

    resources :applications, only: %i[index show]
    # decline_applications
    get ':application/decline_applications/new', to: 'decline_applications#new', as: :decline_application
    post ':application/decline_applications/create', to: 'decline_applications#create', as: :decline_applications
    # proposal
    get ':application/proposals/new', to: 'proposals#new', as: :proposal
    post ':application/proposals/create', to: 'proposals#create', as: :proposals

    resources :decline_applications, only: %i[create]
  end

  namespace :candidates_backoffice do
    root 'home#index'
    resources :candidates, only: %i[show edit update]
    resources :applications, only: %i[index show new create edit update]
    resources :proposals, only: %i[index show]
    resources :jobs, only: %i[show]
  end
end

app/views/shared/_nav_application.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="nav_employee">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="nav_employee" class="navbar-menu">
    <div class="navbar-start">

      <%= link_to companies_path, class: 'navbar-item' do %>
        <i class="mr-1 fas fa-building"></i> Empresas
      <% end %>

      <% if candidate_signed_in? %>
        <%= link_to companies_path, class: 'navbar-item' do %>
          <i class="mr-1 fas fa-briefcase"></i> Vagas
        <% end %>

        <%= link_to candidates_backoffice_applications_path, class: 'navbar-item' do %>
          <i class="mr-1 fas fa-archive"></i> Candidaturas
        <% end %>

        <%= link_to candidates_backoffice_proposals_path, class: 'navbar-item' do %>
          <i class="fa fa-envelope" aria-hidden="true"></i> Propostas
        <% end %>
      <% end %>

    </div>

    <div class="navbar-end">
      <% if candidate_signed_in? %>
        <div class="navbar-item">
          <div class="buttons">
            <%= link_to current_candidate["email"] , candidates_backoffice_candidate_path(current_candidate['id']), class: "button is-light" %>
            
            <%= button_to destroy_candidate_session_path, method: :delete, class: "button is-danger" do %>
              <i class="fas fa-sign-out-alt"></i> Sair
            <% end %>

          </div>
        </div>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">

          <a class="navbar-link">
            Criar conta/Entrar
          </a>

          <div class="navbar-dropdown">
            <%= link_to 'Candidato', candidates_backoffice_root_path, class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link_to  "Recrutador", employees_backoffice_root_path, class: "navbar-item" %>
          </div>
          
        </div>
      <% end %>
    </div>
  </div>
</nav>

<h1>LAYOUT APP</h1>

app/views/shared/_nav_employee.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to employees_backoffice_root_path, class: 'navbar-item' do %>
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    <% end %>
  </div>

  <div id="nav_employee" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to employees_backoffice_applications_path(), class: "navbar-item" do %>
        <i class="mr-1 fas fa-archive"></i> Candidaturas
      <% end %>

      <%= link_to employees_backoffice_jobs_path(), class: "navbar-item" do %>
        <i class="mr-1 fas fa-envelope"></i> Convites
      <% end %>

      <%= link_to employees_backoffice_jobs_path(), class: "navbar-item" do %>
        <i class="mr-1 fas fa-briefcase"></i> Vagas
      <% end %>

    </div>

    <div class="navbar-end">
      <% if employee_signed_in? %>
        <div class="navbar-item">
          <div class="buttons">
            <button class="button is-light">
              <%= current_employee.email %>
            </button>

            <% if current_employee.admin? %>
              <div class="navbar-item has-dropdown is-hoverable">

                <a class="navbar-link">
                  Perfil
                </a>

                <div class="navbar-dropdown">
                  <%= link_to  "perfil do usuário", employees_backoffice_employee_path(current_employee), class: 'navbar-item' %>
                  <hr class="navbar-divider">
                  <%= link_to  "perfil da empresa", profile_employees_backoffice_company_path(current_employee.admin_company_id), class: 'navbar-item' %>
                </div>
                
              </div>
            <% end %>
            
            <%= button_to destroy_employee_session_path, method: :delete, class: "button is-danger" do %>
              <i class="fas fa-sign-out-alt"></i> Sair
            <% end %>

          </div>
        </div>
      <% else %>
        <div class="navbar-item has-dropdown is-hoverable">

          <a class="navbar-link">
            Criar conta
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item">Candidatar-se a vagas?</a>
            <hr class="navbar-divider">
            <%= link_to "Divulgar vagas?", new_employee_registration_path(), class: "navbar-item" %>
          </div>
          
        </div>

        <div class="navbar-item has-dropdown is-hoverable">

          <a class="navbar-link">
            Entrar
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item">Candidato</a>
            <hr class="navbar-divider">
            <%= link_to  "Recrutador", new_employee_session_path, class: "navbar-item" %>
          </div>
          
        </div>
       
      <% end %>
    </div>

  </div>
</nav>

<h1>LAYOUT Employee</h1>